// TTS Configuration based on VoiceRSS API options
module.exports = {
  // Supported languages with their codes and display names
  languages: [
    { code: 'ar-eg', name: 'Arabic (Egypt)' },
    { code: 'ar-sa', name: 'Arabic (Saudi Arabia)' },
    { code: 'bg-bg', name: 'Bulgarian' },
    { code: 'ca-es', name: 'Catalan' },
    { code: 'zh-cn', name: 'Chinese (China)' },
    { code: 'zh-hk', name: 'Chinese (Hong Kong)' },
    { code: 'zh-tw', name: 'Chinese (Taiwan)' },
    { code: 'hr-hr', name: 'Croatian' },
    { code: 'cs-cz', name: 'Czech' },
    { code: 'da-dk', name: 'Danish' },
    { code: 'nl-be', name: 'Dutch (Belgium)' },
    { code: 'nl-nl', name: 'Dutch (Netherlands)' },
    { code: 'en-au', name: 'English (Australia)' },
    { code: 'en-ca', name: 'English (Canada)' },
    { code: 'en-gb', name: 'English (Great Britain)' },
    { code: 'en-in', name: 'English (India)' },
    { code: 'en-ie', name: 'English (Ireland)' },
    { code: 'en-us', name: 'English (United States)' },
    { code: 'fi-fi', name: 'Finnish' },
    { code: 'fr-ca', name: 'French (Canada)' },
    { code: 'fr-fr', name: 'French (France)' },
    { code: 'fr-ch', name: 'French (Switzerland)' },
    { code: 'de-at', name: 'German (Austria)' },
    { code: 'de-de', name: 'German (Germany)' },
    { code: 'de-ch', name: 'German (Switzerland)' },
    { code: 'el-gr', name: 'Greek' },
    { code: 'he-il', name: 'Hebrew' },
    { code: 'hi-in', name: 'Hindi' },
    { code: 'hu-hu', name: 'Hungarian' },
    { code: 'id-id', name: 'Indonesian' },
    { code: 'it-it', name: 'Italian' },
    { code: 'ja-jp', name: 'Japanese' },
    { code: 'ko-kr', name: 'Korean' },
    { code: 'ms-my', name: 'Malay' },
    { code: 'nb-no', name: 'Norwegian' },
    { code: 'pl-pl', name: 'Polish' },
    { code: 'pt-br', name: 'Portuguese (Brazil)' },
    { code: 'pt-pt', name: 'Portuguese (Portugal)' },
    { code: 'ro-ro', name: 'Romanian' },
    { code: 'ru-ru', name: 'Russian' },
    { code: 'sk-sk', name: 'Slovak' },
    { code: 'sl-si', name: 'Slovenian' },
    { code: 'es-mx', name: 'Spanish (Mexico)' },
    { code: 'es-es', name: 'Spanish (Spain)' },
    { code: 'sv-se', name: 'Swedish' },
    { code: 'ta-in', name: 'Tamil' },
    { code: 'th-th', name: 'Thai' },
    { code: 'tr-tr', name: 'Turkish' },
    { code: 'vi-vn', name: 'Vietnamese' }
  ],

  // Audio formats with their descriptions
  audioFormats: [
    { code: '8khz_8bit_mono', description: '8 kHz, 8 Bit, Mono' },
    { code: '8khz_8bit_stereo', description: '8 kHz, 8 Bit, Stereo' },
    { code: '8khz_16bit_mono', description: '8 kHz, 16 Bit, Mono' },
    { code: '8khz_16bit_stereo', description: '8 kHz, 16 Bit, Stereo' },
    { code: '11khz_8bit_mono', description: '11 kHz, 8 Bit, Mono' },
    { code: '11khz_8bit_stereo', description: '11 kHz, 8 Bit, Stereo' },
    { code: '11khz_16bit_mono', description: '11 kHz, 16 Bit, Mono' },
    { code: '11khz_16bit_stereo', description: '11 kHz, 16 Bit, Stereo' },
    { code: '12khz_8bit_mono', description: '12 kHz, 8 Bit, Mono' },
    { code: '12khz_8bit_stereo', description: '12 kHz, 8 Bit, Stereo' },
    { code: '12khz_16bit_mono', description: '12 kHz, 16 Bit, Mono' },
    { code: '12khz_16bit_stereo', description: '12 kHz, 16 Bit, Stereo' },
    { code: '16khz_8bit_mono', description: '16 kHz, 8 Bit, Mono' },
    { code: '16khz_8bit_stereo', description: '16 kHz, 8 Bit, Stereo' },
    { code: '16khz_16bit_mono', description: '16 kHz, 16 Bit, Mono' },
    { code: '16khz_16bit_stereo', description: '16 kHz, 16 Bit, Stereo' },
    { code: '22khz_8bit_mono', description: '22 kHz, 8 Bit, Mono' },
    { code: '22khz_8bit_stereo', description: '22 kHz, 8 Bit, Stereo' },
    { code: '22khz_16bit_mono', description: '22 kHz, 16 Bit, Mono' },
    { code: '22khz_16bit_stereo', description: '22 kHz, 16 Bit, Stereo' },
    { code: '24khz_8bit_mono', description: '24 kHz, 8 Bit, Mono' },
    { code: '24khz_8bit_stereo', description: '24 kHz, 8 Bit, Stereo' },
    { code: '24khz_16bit_mono', description: '24 kHz, 16 Bit, Mono' },
    { code: '24khz_16bit_stereo', description: '24 kHz, 16 Bit, Stereo' },
    { code: '32khz_8bit_mono', description: '32 kHz, 8 Bit, Mono' },
    { code: '32khz_8bit_stereo', description: '32 kHz, 8 Bit, Stereo' },
    { code: '32khz_16bit_mono', description: '32 kHz, 16 Bit, Mono' },
    { code: '32khz_16bit_stereo', description: '32 kHz, 16 Bit, Stereo' },
    { code: '44khz_8bit_mono', description: '44 kHz, 8 Bit, Mono' },
    { code: '44khz_8bit_stereo', description: '44 kHz, 8 Bit, Stereo' },
    { code: '44khz_16bit_mono', description: '44 kHz, 16 Bit, Mono' },
    { code: '44khz_16bit_stereo', description: '44 kHz, 16 Bit, Stereo' },
    { code: '48khz_8bit_mono', description: '48 kHz, 8 Bit, Mono' },
    { code: '48khz_8bit_stereo', description: '48 kHz, 8 Bit, Stereo' },
    { code: '48khz_16bit_mono', description: '48 kHz, 16 Bit, Mono' },
    { code: '48khz_16bit_stereo', description: '48 kHz, 16 Bit, Stereo' },
    { code: 'alaw_8khz_mono', description: 'ALaw, 8 kHz, Mono' },
    { code: 'alaw_8khz_stereo', description: 'ALaw, 8 kHz, Stereo' },
    { code: 'alaw_11khz_mono', description: 'ALaw, 11 kHz, Mono' },
    { code: 'alaw_11khz_stereo', description: 'ALaw, 11 kHz, Stereo' },
    { code: 'alaw_22khz_mono', description: 'ALaw, 22 kHz, Mono' },
    { code: 'alaw_22khz_stereo', description: 'ALaw, 22 kHz, Stereo' },
    { code: 'alaw_44khz_mono', description: 'ALaw, 44 kHz, Mono' },
    { code: 'alaw_44khz_stereo', description: 'ALaw, 44 kHz, Stereo' },
    { code: 'ulaw_8khz_mono', description: 'uLaw, 8 kHz, Mono' },
    { code: 'ulaw_8khz_stereo', description: 'uLaw, 8 kHz, Stereo' },
    { code: 'ulaw_11khz_mono', description: 'uLaw, 11 kHz, Mono' },
    { code: 'ulaw_11khz_stereo', description: 'uLaw, 11 kHz, Stereo' },
    { code: 'ulaw_22khz_mono', description: 'uLaw, 22 kHz, Mono' },
    { code: 'ulaw_22khz_stereo', description: 'uLaw, 22 kHz, Stereo' },
    { code: 'ulaw_44khz_mono', description: 'uLaw, 44 kHz, Mono' },
    { code: 'ulaw_44khz_stereo', description: 'uLaw, 44 kHz, Stereo' }
  ],

  // Audio codecs
  codecs: ['MP3', 'WAV', 'AAC', 'OGG', 'CAF'],
  
  // Rate options (-10 to 10)
  rates: [-10, -5, 0, 5, 10],
  
  // Base64 encoding option
  base64: [true, false],
  
  // Default values
  defaults: {
    voice: 'en-us',
    speed: 0,
    format: '16khz_16bit_stereo',
    codec: 'MP3',
    base64: false
  }
};
